[package]
name = "xps5x-loader"
description = "PS5 binary loader — SELF/ELF/PKG parser and program segment loader"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
xps5x-core = { workspace = true }
goblin = { workspace = true }
scroll = { workspace = true }
bytemuck = { workspace = true }
zerocopy = { workspace = true }
memmap2 = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
bitflags = { workspace = true }
