[package]
name = "xps5x-io"
description = "PS5 I/O complex emulation — SSD decompression and DMA"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
xps5x-core = { workspace = true }
lz4_flex = { workspace = true }
zstd = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
